# Generated by Django 3.2.6 on 2021-09-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('login_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('password_conf', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.IntegerField(default=0, null=True)),
                ('end_time', models.IntegerField(default=0, null=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
