# Generated by Django 3.2.7 on 2021-09-09 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoursCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'AMCO'), ('F', 'FPB')], default='A', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('E', 'East'), ('W', 'West')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150, null=True)),
                ('sector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sector')),
            ],
        ),
        migrations.AddField(
            model_name='workentry',
            name='hourscode_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.hourscode'),
        ),
    ]
