# Generated by Django 3.2.7 on 2021-09-10 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20210909_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='sector_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_conf',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='workentry',
            name='hourscode_id',
        ),
        migrations.AddField(
            model_name='location',
            name='sector',
            field=models.CharField(choices=[('E', 'East'), ('W', 'West')], default='East', max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='email_conf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workentry',
            name='hourscode',
            field=models.CharField(choices=[('A', 'AMCO'), ('F', 'FPB')], default='AMCO', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
