# Generated by Django 3.2.7 on 2021-09-12 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210910_0915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HoursCode',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.AddField(
            model_name='workentry',
            name='location',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
    ]
